#!/bin/bash
#SBATCH -p gpu_med
#SBATCH -c 16
#SBATCH -w dsh09gvu001
#SBATCH --mem 128G
module load apps/anaconda/3
source activate myenv
python scripts/perm_importance.py --adverse-event CYTO

# ##############################
# Template1
# SBATCH -p med
# SBATCH -c 64
# SBATCH -w dsh09ana003
# SBATCH --mem 512G
# ##############################
# Template2
# SBATCH -p gpu_med
# SBATCH -c 16
# SBATCH -w dsh09gvu001
# SBATCH --mem 128G
# ##############################
